name: Build Kernel for MIPSEL

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

    workflow_dispatch:

jobs:
      build-mipsel:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout source
            uses: actions/checkout@v4
    
          - name: Install dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y build-essential git
    
          - name: Download musl installer
            run: |
              git clone https://github.com/richfelker/musl-cross-make.git
    
          - name: Configure musl and build toolchain
            run: |
              cd musl-cross-make
              cp ../musl.config.mipsel ./config.mak
              make -j$(nproc)
    
          - name: Install toolchain
            run: |
              cd musl-cross-make
              sudo make install
    
          - name: Configure kernel
            run: |
              mkdir -p build/mipsel
              cp config.mipsel build/mipsel/.config
    
          - name: Build kernel
            run: |
              make ARCH=mips CROSS_COMPILE=/opt/cross/mipsel-linux-musl/bin/mipsel-linux-musl- O=./build/mipsel -j$(nproc)
    
          - name: Archive kernel
            run: |
              tar -czf kernel-mipsel.tar.gz  -C ./build/mipsel vmlinux
              echo "Kernel archive created: kernel-mipsel.tar.gz"
    
          - name: Upload kernel artifact
            uses: actions/upload-artifact@v4
            with:
              name: kernel-mipsel
              path: kernel-mipsel.tar.gz